// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQ0wBeWkQ-U0hXEwYA3aS9lZUhr4Wsu0',
    appId: '1:188667015579:web:34a26e8d7180273e52b13e',
    messagingSenderId: '188667015579',
    projectId: 'nhung-btl-tactc',
    authDomain: 'nhung-btl-tactc.firebaseapp.com',
    storageBucket: 'nhung-btl-tactc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfrMyBfo5TAN10MYJnnH04JriZtVgIyoQ',
    appId: '1:188667015579:android:cf75273a155054ac52b13e',
    messagingSenderId: '188667015579',
    projectId: 'nhung-btl-tactc',
    storageBucket: 'nhung-btl-tactc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbQJIXLMPymL_HReyb46qgtdTCPHqXN2Q',
    appId: '1:188667015579:ios:68ce7478f619c84652b13e',
    messagingSenderId: '188667015579',
    projectId: 'nhung-btl-tactc',
    storageBucket: 'nhung-btl-tactc.firebasestorage.app',
    iosBundleId: 'com.example.petFeederApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbQJIXLMPymL_HReyb46qgtdTCPHqXN2Q',
    appId: '1:188667015579:ios:68ce7478f619c84652b13e',
    messagingSenderId: '188667015579',
    projectId: 'nhung-btl-tactc',
    storageBucket: 'nhung-btl-tactc.firebasestorage.app',
    iosBundleId: 'com.example.petFeederApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNQ0wBeWkQ-U0hXEwYA3aS9lZUhr4Wsu0',
    appId: '1:188667015579:web:48b09eae43095b5752b13e',
    messagingSenderId: '188667015579',
    projectId: 'nhung-btl-tactc',
    authDomain: 'nhung-btl-tactc.firebaseapp.com',
    storageBucket: 'nhung-btl-tactc.firebasestorage.app',
  );
}
